In [1]:
from src.visualisation.visualiser import Visualiser
from src.algorithms.Astar import Astar
from src.algorithms.Dijkstra import Dijkstra
from src.algorithms.BFS import BFS
import numpy as np

pygame 2.6.1 (SDL 2.28.4, Python 3.11.8)
Hello from the pygame community. https://www.pygame.org/contribute.html


In [2]:

from src.algorithms.Dijkstra import Dijkstra
from src.algorithms.BFS import BFS
import numpy as np

grid = np.ones((20,20))

grid[1:5, 1:5] = -1
np.set_printoptions(linewidth=np.inf)

def heuristic (a,b):
    #differnece
    return ((a[0]-b[0])**2 + (a[1]-b[1])**2)**0.5

Astart = Astar(start=(0,0), end=(12,10), map = grid,heuristic = heuristic )
Dijkstrat = Dijkstra(start=(0,0), end=(12,10), map = grid)
BFSt = BFS(start=(0,0), end=(12,10), map = grid)
path1 = Astart.run_algorithm()
path2 = Dijkstrat.run_algorithm()
path3 = BFSt.run_algorithm()

for coord in path1:
    grid[coord] = 5
for coord in path2:
    grid[coord] = 4
for coord in path3:
    grid[coord] = 3
grid[0,0] = 0
grid[12,10] = 0
print(grid)
print(path1, '\n',path2,'\n', path3)

[[ 0.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 3. -1. -1. -1. -1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 3. -1. -1. -1. -1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 3. -1. -1. -1. -1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 3. -1. -1. -1. -1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  3.  3.  3.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  5.  1.  3.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  5.  1.  3.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  5.  1.  3.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  5.  1.  3.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  5.  1.  3.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  5.  1.  3.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1